x-prod-base: &prod-base
  build:
    context: .
  image: ${COMPOSE_PROJECT_NAME:-app}
  volumes:
    - nuget_packages:/root/.nuget/packages
  depends_on:
    postgres:
      condition: service_healthy
  restart: unless-stopped

x-dev-base: &dev-base
  build:
    context: .
  volumes:
    - .:/app
    - nuget_packages:/root/.nuget/packages
  tty: true
  stdin_open: true

services:
  prod-all:
    <<: *prod-base
    build:
      context: .
      target: prod-all
    image: prod-all
    ports:
      - "1212:1212"

  prod-server:
    <<: *prod-base
    build:
      context: .
      target: prod-server
    image: prod-server
    ports:
      - "1212:1212"

  prod-client:
    <<: *prod-base
    build:
      context: .
      target: prod-client
    image: prod-client

  dev-all:
    <<: *dev-base
    build:
      context: .
      target: dev-all
    image: dev-all
    ports:
      - "1212:1212"

  dev-server:
    <<: *dev-base
    build:
      context: .
      target: dev-server
    image: dev-server
    ports:
      - "1212:1212"

  dev-client:
    <<: *dev-base
    build:
      context: .
      target: dev-client
    image: dev-client

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  nuget_packages:
  postgres_data:
